blank_issues_enabled: false
contact_links:
  - name: 🤔 Help & Questions
    url: https://github.com/schlpr0k/IronJump
    about: Ask general support or usage questions in the IronJump Discussion forums
